package: mmedia_chain
version: '1.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/media_chain

requires:
    redaxo: '^5.18.0'
    packages:
        media_manager: '^2.11.0'
    php:
        version: '>=8.1'
